[package]
name = "microtile_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
either = { version = "1.9.0", features = [] }
heapless = "0.7.16"

[dev-dependencies]
anyhow = "1.0.75"
